In [1]:
import torch
import numpy as np

pytorch tensors can be created from regular Python lists

In [7]:
data = [[1, 2], [3, 4], [5, 6]]
x_data = torch.tensor(data)

In [ ]:
print(x_data)

pytorch tensors can also be created from numpy arrays

In [11]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]
 [5 6]]
tensor([[1, 2],
        [3, 4],
        [5, 6]])


takes a matrix with the shape of x_data and fills it with 1s

In [12]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1],
        [1, 1]])


same concept: takes a matrix with the shape of x_data and fills it with random values

In [18]:
x_random = torch.rand_like(x_data, dtype=torch.float)
print(x_random)

tensor([[0.7861, 0.5674],
        [0.4260, 0.2070],
        [0.8998, 0.1916]])


can also pass in shape to create a random matrix

In [78]:
shape = (5, 5)
x_random = torch.rand(shape)
print(x_random)
x_random = torch.rand((4,4))
print(x_random)

tensor([[0.2077, 0.5451, 0.5921, 0.5688, 0.8015],
        [0.6561, 0.0421, 0.9773, 0.3372, 0.4976],
        [0.1965, 0.2252, 0.9954, 0.8470, 0.6156],
        [0.3695, 0.6164, 0.7092, 0.7987, 0.9736],
        [0.4124, 0.9164, 0.1779, 0.5271, 0.5687]])
tensor([[0.1389, 0.1310, 0.6285, 0.5153],
        [0.7197, 0.7796, 0.4375, 0.7488],
        [0.1992, 0.3602, 0.0545, 0.2700],
        [0.1405, 0.6447, 0.4186, 0.5595]])


passing in shape to ones() to create a matrix full of 1s, the matrix matches the dimension shape

In [22]:
shape_ones = torch.ones(shape)
print(shape_ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


passing in shape to zeros to create a matrix of 0s, the matrix matches the dimension shape

In [24]:
shape_zeros = torch.zeros(shape)
print(shape_zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


attributes of a tensor

In [32]:
tensor = torch.rand(3, 4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


check if we're able to use the gpu

In [37]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(tensor.device)
else :
  print('cuda is not available')

cuda is not available


using numpy array slicing syntax x: means go from row or column x all the way to the end row / column

In [58]:
tensor = torch.ones(5, 5)
tensor[0:,2:] = 0
print(tensor)
print(tensor.size())

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])
torch.Size([5, 5])


concatenating two tensors

In [65]:
combined_tensor = torch.cat([tensor, tensor], dim = 1)
print(combined_tensor)

tensor([[1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.]])


matrix multiplication

In [67]:
print(tensor * tensor)
print(tensor.mul(tensor))

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])
tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])


.T performs a transpose, for 2D matrices .T has no parameters because you simply swap the rows and columns

In [74]:
print(tensor, "\n")
print(tensor.T, "\n")
tensor = tensor * tensor.T
print(tensor)

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 
 hello
tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 

tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


in place operations, signified by the use of an underscore at the end of the function

In [76]:
print(tensor, "\n")
print(tensor.add_(5), "\n")
print(tensor.sub_(3), "\n")

tensor([[6., 6., 5., 5., 5.],
        [6., 6., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]) 

tensor([[11., 11., 10., 10., 10.],
        [11., 11., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]) 

tensor([[8., 8., 7., 7., 7.],
        [8., 8., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]]) 

