Creating a range of tensors and tensors-like

In [2]:
import torch

In [3]:
torch.arange(0, 10)
torch.arange(start=-30, end=1000, step=37) # default step is 1

tensor([-30,   7,  44,  81, 118, 155, 192, 229, 266, 303, 340, 377, 414, 451,
        488, 525, 562, 599, 636, 673, 710, 747, 784, 821, 858, 895, 932, 969])

# tensors like
*_like(torch.Tensor) functions create a new tensor with the same shape and dtype as the input tensor but with different values.

In [4]:
x = torch.rand(4, 5)
y = torch.ones_like(x)
z = torch.zeros_like(x)
a = torch.randn_like(x)

print(x, "\n\n", y, "\n\n", z)

tensor([[0.8558, 0.2671, 0.6652, 0.3725, 0.5519],
        [0.2218, 0.1913, 0.5889, 0.4114, 0.2678],
        [0.8351, 0.8517, 0.9843, 0.3606, 0.9441],
        [0.8749, 0.0070, 0.6477, 0.8881, 0.3180]]) 

 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
b = torch.arange(0, 600, 5, dtype=float)
c = torch.randn_like(b)
print(b, "\n\n", c)

tensor([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
         60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105., 110., 115.,
        120., 125., 130., 135., 140., 145., 150., 155., 160., 165., 170., 175.,
        180., 185., 190., 195., 200., 205., 210., 215., 220., 225., 230., 235.,
        240., 245., 250., 255., 260., 265., 270., 275., 280., 285., 290., 295.,
        300., 305., 310., 315., 320., 325., 330., 335., 340., 345., 350., 355.,
        360., 365., 370., 375., 380., 385., 390., 395., 400., 405., 410., 415.,
        420., 425., 430., 435., 440., 445., 450., 455., 460., 465., 470., 475.,
        480., 485., 490., 495., 500., 505., 510., 515., 520., 525., 530., 535.,
        540., 545., 550., 555., 560., 565., 570., 575., 580., 585., 590., 595.],
       dtype=torch.float64) 

 tensor([-0.1693, -0.3022, -0.8590,  0.2553,  0.0477, -2.0304,  0.4631, -1.2510,
         0.0936,  0.8622, -0.3766,  1.3935, -0.7088,  0.5201, -0.0901,  0.9948,
        

In [6]:
int_tensor = torch.tensor([3, 6, 7], dtype=None)
print(int_tensor.dtype)

float_tensor = torch.tensor([3.0, 6, 7], dtype=None, device=None, requires_grad=False)
print(float_tensor)
print(float_tensor.dtype)

float_tensor_half = float_tensor.type(torch.float16)
print(float_tensor_half)

# we can use element wise multiplication because the two tensors are of the same shape.
# Notice that we aren't able to perform float_tensor @ float_tensor_half (matrix multiplication)
print(float_tensor * float_tensor_half)

torch.int64
tensor([3., 6., 7.])
torch.float32
tensor([3., 6., 7.], dtype=torch.float16)
tensor([ 9., 36., 49.])


note: tensor datatypes are one of the issues that you'll run into the most with PyTorch and deep learning in general

most common issues
1. tensors aren't the right datatype
2. tensors aren't the right shape
3. tensors aren't on the right device

In [17]:
some_tensor = torch.rand(3, 1, 3, 4, 25, 4)

print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Shape of tensor: {some_tensor.size()}") # notice that .shape and .size() represent the same thing (shape of the tensor)
print(f"Tensor is on device: {some_tensor.device}")
print(f"Tensor has rank: {some_tensor.ndim}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 1, 3, 4, 25, 4])
Shape of tensor: torch.Size([3, 1, 3, 4, 25, 4])
Tensor is on device: cpu
Tensor has dimenion: 6
