<a href="https://colab.research.google.com/github/ANDREW-Li-33/pytorch-learning/blob/main/zero-to-mastery-daniel-bourke/video_follow_along_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Aggregation (finding the min, max, mean, sum)

aggregating many numbers in a tensor into one number (ex. min, max, mean)

In [ ]:
import torch

In [63]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
min = torch.min(x)
min_again = x.min()
max = torch.max(x)
max_again = x.max()
print(min, min_again, max, max_again)

tensor(0) tensor(0) tensor(90) tensor(90)


notice that this won't work! the mean() method won't work on tensors of data type Long

In [ ]:
x.mean()

AttributeError: attribute 'dtype' of 'torch._C.TensorBase' objects is not writable

In [ ]:
torch.mean(x.type(torch.float32)) # note the use of the .type() method

tensor(45.)

In [ ]:
x.mean*()

In [19]:
y = torch.arange(0, 100, 10, dtype=float)
y.mean()
max = torch.max(x)

tensor(9)

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Positional min and max

In [22]:
torch.argmin(x), torch.argmax(x) # returns position (indices) of the min / max

(tensor(0), tensor(9))

In [20]:
max, indices = torch.max(x, dim=0)
indices

tensor(9)

In [35]:
b = torch.rand(3, 6)
print(b, torch.argmin(b), torch.min(b))

tensor([[0.2550, 0.4939, 0.2751, 0.3617, 0.1536, 0.2788],
        [0.0759, 0.1352, 0.1519, 0.4050, 0.0367, 0.6887],
        [0.2218, 0.7447, 0.2840, 0.2979, 0.5985, 0.6600]]) tensor(10) tensor(0.0367)


## reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape, but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target torch.tensor
* Permuate - return a view of the input with dimensions permuted

In [38]:
c = torch.arange(1., 10.)
c, c.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [41]:
# add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [43]:
x_reshaped_again = x.reshape(10, 1)
x_reshaped_again, x_reshaped_again.shape # note that the reshape has to be compatible with the original size!

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]))

In [44]:
y = x.reshape(5, 2)
y, y.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([5, 2]))

In [64]:
f = x.reshape(2, 5)
f

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [72]:
# changing g change x because a view of a tensor points to the original tensor
g = x.view(2, 5)

g[:, 0] = 5
g, x

(tensor([[ 5, 10, 20, 30, 40],
         [ 5, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90]))

In [80]:
x_stacked = torch.stack([x, x, x, x], dim=1) # default dimension is 0
x_stacked

tensor([[ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [ 5,  5,  5,  5],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [82]:
x_stacked = torch.hstack([x, x, x, x])
x_stacked

tensor([ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90,  5, 10, 20, 30, 40,  5, 60, 70,
        80, 90,  5, 10, 20, 30, 40,  5, 60, 70, 80, 90,  5, 10, 20, 30, 40,  5,
        60, 70, 80, 90])

In [83]:
x_stacked = torch.vstack([x, x, x, x])
x_stacked

tensor([[ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40,  5, 60, 70, 80, 90]])

In [86]:
# torch.squeeze() - removes all single dimensions from an input tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [90]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [94]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [95]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [102]:
r = torch.zeros(1, 2, 3, 1, 4)
j = torch.squeeze(r) # indices / dimensions 0 and 3 are 1. Therefore, they are removed
print(j.size())

k = torch.squeeze(r, 3) # index 3 (dimension 3) is 1. therefore, it is removed
print(k.size())

k = torch.squeeze(r, 2)
print(k.size()) # note that k remains the same as r because dim 2 (index 2 in the size list) is not 1. Squeeze will only remove the specified dimension if it's size 1

torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([1, 2, 3, 1, 4])


In [105]:
# unsqueezing

print(f"squeezed tensor: {j}")
print(f"squeezed tensor shape: {j.shape}")

# basically inserting a 1 at input index / dimension in the shape list
j_unsqueezed = j.unsqueeze(dim=1)

print(f"unsqueezed tensor: {j_unsqueezed}")
print(f"unsqueezed tensor shape: {j_unsqueezed.shape}")

squeezed tensor: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
squeezed tensor shape: torch.Size([2, 3, 4])
unsqueezed tensor: tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])
unsqueezed tensor shape: torch.Size([2, 1, 3, 4])


## permuting

In [108]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [110]:
x_permuted = torch.permute(x, (2, 0, 1))
x_permuted.size()

torch.Size([5, 2, 3])

In [113]:
# a practical example, working with image tneosrs

image_tensor = torch.rand(224, 224, 3)

image_permuted = image_tensor.permute(2, 0, 1)
image_permuted.shape

torch.Size([3, 224, 224])

In [115]:
image_tensor[0, 0, 0] =  5422324
image_permuted[0, 0, 0] # note that the value in image_permuted changes as well because tensor.permute returns a view, and views point to the original tensor

tensor(5422324.)

## indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [120]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [121]:
# indexing x, notice there's one less pair of brakcets
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [122]:
x[0, 0] # same as x[0][0]

tensor([1, 2, 3])

In [123]:
x[0][1]

tensor([4, 5, 6])

In [124]:
x[0][1][0]

tensor(4)

In [125]:
x[0][2][2]

tensor(9)

In [126]:
# you can also use ":"" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [127]:
# get all values of 0th and first dimsions, but only 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [128]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [129]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [130]:
# index on x to return 9
x[:, 2, 2]

tensor([9])

In [132]:
# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])