In Google Colab, Go to the tool bar -> Runtime -> Change runtime type -> select a GPU


`!nvidia-smi` shows information about the current status of the NVIDIA GPU
if you aren't connected to a GPU, you'll get

```
nvidia-smi: command not found
```

prepending a cell with ! runs the content of the cell as a shell command



In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


Introduction to Tensors

In [5]:
# scalar tensor
scalar = torch.tensor(7)
scalar
scalar.ndim
scalar.item() # get tensor back as Python integer

7

In [6]:
# vector
vector = torch.tensor([7, 7]) # passing in a list
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [11]:
# TENSOR, remember that that torch.tensor() only takes in one argument!
TENSOR = torch.tensor([[1, 2, 3],
                      [3, 4, 4],
                      [4, 5, 5]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

TENSOR2 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(TENSOR2.ndim)
print(TENSOR2.shape)

TENSOR3 = torch.tensor([[[3], [4], [5]]])
print(TENSOR3.ndim)
print(TENSOR3.shape)

tensor([[1, 2, 3],
        [3, 4, 4],
        [4, 5, 5]])
2
torch.Size([3, 3])
2
torch.Size([2, 3])
3
torch.Size([1, 3, 1])


Random tensors are actually really important! The way that many Neural Networks learn is by starting with tensors full of random numbers and continuously changing those random numbers to better represent the data!

In [15]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.3640, 0.0489, 0.9196, 0.5182],
        [0.8130, 0.5930, 0.5555, 0.1911],
        [0.0063, 0.1490, 0.1652, 0.0125]])
torch.float32


create a random tensor with a similar shape to an image tensor

In [26]:
random_image_size_tensor = torch.rand(224, 224, 3) # notice you don't have to explicitly use the size parameter because of positional arguments ()
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [22]:
zeros = torch.zeros([3, 4], dtype=int)
zeros

zeros_again = torch.zeros(size=(3,4), dtype=bool)
zeros_again

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])