<a href="https://colab.research.google.com/github/ANDREW-Li-33/pytorch-learning/blob/main/video_follow_along_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Operations
- addition
- subtraction
- multiplication (element-wise)
- division
- matrix multiplication

In [3]:
import torch

In [18]:
a = torch.tensor([1, 2, 3])
print(a + 100)
print(a - 100)
print(a * 100) # element wise multiplication (multiplying by a scalar)
print(a / 100)
a = a * 20
print(a)
print(torch.mul(a, 10)) # check out the documentation for more
print(torch.log(a))

tensor([101, 102, 103])
tensor([-99, -98, -97])
tensor([100, 200, 300])
tensor([0.0100, 0.0200, 0.0300])
tensor([20, 40, 60])
tensor([200, 400, 600])
tensor([2.9957, 3.6889, 4.0943])


matrix multiplication. you can think of matrix multiplication as a chain of dot products

In [21]:
tensor = torch.tensor([1, 2, 3])

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.99 ms, sys: 0 ns, total: 1.99 ms
Wall time: 1.55 ms


tensor(14)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 91 µs, sys: 7 µs, total: 98 µs
Wall time: 102 µs


tensor(14)

Notice how much faster PyTorch's built-in matrix multiplication function is compared to manually computing the matrix mutliplication
Also notice that this isn't a valid matrix multipilication (inner dimensions must match, but the operation above is multipyling 1x3 by 1x3 and the inner 3 and 1 do not match), but if PyTorch notices that both input tensors are one-dimensional, it will compute the dot product

matrix multiplication in PyTorch is represented by the @ operator
you can also write torch.matmul(tensor, tensor) or torch.mm(tensor, tensor)

to fix tensor shape issues, we can manipulate the shape of our tensors using Transpose

In [49]:
print(tensor)
print(tensor.T) # notice that 1D tensors don't change when transposed in PyTorch

tensor([1, 2, 3])
tensor([1, 2, 3])


In [56]:
tensor_2 = torch.rand([4, 2])
print(tensor_2)
print(tensor_2.T)
print(tensor_2.shape)
print(tensor_2.T.shape)

tensor([[0.4243, 0.7791],
        [0.2295, 0.0784],
        [0.1545, 0.6344],
        [0.9784, 0.6463]])
tensor([[0.4243, 0.2295, 0.1545, 0.9784],
        [0.7791, 0.0784, 0.6344, 0.6463]])
torch.Size([4, 2])
torch.Size([2, 4])


In [58]:
tensor_3 = torch.rand([4, 2, 3])
print(tensor_3)
print(tensor_3.T) # notice that we can transpose tensors of higher dimensions

tensor([[[0.8737, 0.7488, 0.1369],
         [0.7717, 0.5756, 0.7148]],

        [[0.7895, 0.9956, 0.2779],
         [0.4819, 0.5086, 0.2404]],

        [[0.0453, 0.3200, 0.0352],
         [0.8791, 0.3980, 0.2916]],

        [[0.3922, 0.8529, 0.7900],
         [0.0466, 0.7655, 0.8386]]])
tensor([[[0.8737, 0.7895, 0.0453, 0.3922],
         [0.7717, 0.4819, 0.8791, 0.0466]],

        [[0.7488, 0.9956, 0.3200, 0.8529],
         [0.5756, 0.5086, 0.3980, 0.7655]],

        [[0.1369, 0.2779, 0.0352, 0.7900],
         [0.7148, 0.2404, 0.2916, 0.8386]]])
