<a href="https://colab.research.google.com/github/ANDREW-Li-33/pytorch-learning/blob/main/zero-to-mastery-daniel-bourke/video_follow_along_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

## PyTorch Tensors and NumPy

In [ ]:
# changing numpy arrays to pytorch tensors -> torch.from_numpy(ndarray)
# changing pytorch tensors to numpy arrays -> torch.Tensor.numpy()

In [3]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless otherwise specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
array.dtype # default numpy data type is float64

dtype('float64')

In [5]:
torch.arange(1.0, 8.0).dtype

torch.float32

## Reproducibility (taking the random out of random)

Brief overview of how a NN works
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch, we use a **random seed**, which "flavors" the randomness

In [126]:
randA = torch.rand(3, 4)
randB = torch.rand(3, 4)

print(randA)
print(randB)
print(randA == randB) # notice that it's highly unlikely we'll have any true elements

tensor([[0.7755, 0.1701, 0.4300, 0.2366],
        [0.8610, 0.5037, 0.3542, 0.2710],
        [0.4556, 0.6376, 0.2989, 0.1467]])
tensor([[0.6134, 0.4103, 0.2558, 0.4705],
        [0.9995, 0.8711, 0.6132, 0.8939],
        [0.2354, 0.3334, 0.9869, 0.9263]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [161]:
# making random but reproducible tensors
RANDOM_SEED = 4221324525 # this number is arbitrary
torch.manual_seed(RANDOM_SEED)
randC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # note that we have to set the manual seed each time
randD = torch.rand(3, 4)

print(randC)
print(randD)
print(randC == randD)

tensor([[0.5658, 0.3781, 0.6306, 0.3142],
        [0.0412, 0.6954, 0.9037, 0.4140],
        [0.2526, 0.3912, 0.1842, 0.7956]])
tensor([[0.5658, 0.3781, 0.6306, 0.3142],
        [0.0412, 0.6954, 0.9037, 0.4140],
        [0.2526, 0.3912, 0.1842, 0.7956]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Since PyTorch is capable of running computuations on both the GPU and CPU, it's best practice to set up device agnostic code (run on GPU if available, otherwise run on CPU)

In [162]:
# Checking for GPU access
torch.cuda.is_available()

False

In [164]:
# setting up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [163]:
torch.cuda.device_count()

0